---
title: "Coursera MOOC_Reproducible Research_Course Project 1"
output: html_document
---

##Loading and preprocessing the data
```{r echo = TRUE}
setwd("F:/Personal/Coursera/Data Science/Reproducible Rsrch/W1/Project")
unzip(zipfile="activity.zip")
ActivityData <- read.csv("activity.csv", header = TRUE)
```


##Load relevant libraries.
```{r echo = TRUE}
library(ggplot2)
library(Hmisc)
```


##What is mean total number of steps taken per day?
```{r echo=TRUE}
stepsByDay <- tapply(ActivityData$steps, ActivityData$date, sum, na.rm = TRUE)
qplot(stepsByDay, xlab = "Total Steps per day", ylab = "Frequency using binwidth 500", binwidth = 500)
mean(stepsByDay, na.rm = TRUE)
median(stepsByDay,  na.rm = TRUE)
```


##What is the average daily activity pattern?
```{r echo=TRUE}
averageTimeperBlock <- aggregate(x = list(meanSteps = ActivityData$steps), by = list(interval = ActivityData$interval), FUN = mean, na.rm = TRUE)
ggplot(data = averageTimeperBlock, aes(x=interval, y=meanSteps)) +
 geom_line() +
 xlab("5 minutes interval") +
 ylab("average number of steps taken")
```


###Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps
```{r echo=TRUE}
averageTimeperBlock[which.max(averageTimeperBlock$meanSteps),]
```


##Imputing missing values
```{r echo=TRUE}
ImputedActivityData <- ActivityData
ImputedActivityData$steps <- impute(ActivityData$steps, fun = mean)
stepsByDayImputed <- tapply(ImputedActivityData$steps, ImputedActivityData$date, sum)
qplot(stepsByDayImputed, xlab= "Total steps per day (Imputed)", ylab = "Frequency using binwidth 500", binwidth = 500)
stepsByDayMeanImputed <- mean(stepsByDayImputed)
stepsByDayMedianImputed <- median(stepsByDayImputed)
```


##Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
weekday_or_weekend <- function(date) { 
 day <- weekdays(date)
 if(day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
 return("weekday")
 else if (day %in% c("Sunday", "Saturday"))
 return("weekend")
 else
 stop("invalid date")
 }

ImputedActivityData$date <- as.Date(ImputedActivityData$date)
ImputedActivityData$day <- sapply(ImputedActivityData$date, FUN = weekday_or_weekend)
AveragedImputedActivityData <- aggregate(steps ~ interval + day, data = ImputedActivityData, mean)
ggplot(AveragedImputedActivityData, aes(interval, steps)) + geom_line() + xlab("5 minute interval") + ylab("Number of steps")
```